export const properties = [
  {
    id: 1,
    type: "Sale",
    title: "Olive Garden Villa",
    location: "Beirut, Lebanon",
    price: "$950,000",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80",
    beds: 5,
    baths: 4,
    area: "420m²",
    description: "A stunning Mediterranean villa nestled in the hills of Beirut, featuring panoramic sea views, a private pool, and lush olive gardens. This masterpiece combines traditional Lebanese architecture with modern luxury finishes.",
    features: ["Private Pool", "Sea View", "Smart Home", "Garden", "Garage", "Security System"],
    country: "Lebanon",
  },
  {
    id: 2,
    type: "Sale",
    title: "Karachi Luxury Estate",
    location: "DHA, Karachi",
    price: "$500,000",
    image: "https://images.unsplash.com/photo-1600607687940-4e5a994e5373?w=800&q=80",
    beds: 4,
    baths: 3,
    area: "280m²",
    description: "An exquisite modern estate in the heart of DHA Karachi, offering contemporary design, premium materials, and a serene lifestyle. Perfect for discerning buyers seeking the best of Karachi's real estate.",
    features: ["Modern Kitchen", "Home Office", "Rooftop Terrace", "Garage", "Generator", "CCTV"],
    country: "Pakistan",
  },
  {
    id: 3,
    type: "Rent",
    title: "Downtown Dubai Penthouse",
    location: "Dubai, UAE",
    price: "$8,000/mo",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80",
    beds: 3,
    baths: 3,
    area: "200m²",
    description: "An ultra-luxury penthouse in the heart of Downtown Dubai with breathtaking Burj Khalifa views. Features floor-to-ceiling glass walls, a private terrace, and access to world-class amenities.",
    features: ["Burj Khalifa View", "Private Terrace", "Concierge", "Gym Access", "Pool Access", "Parking"],
    country: "UAE",
  },
  {
    id: 4,
    type: "Sale",
    title: "Lahore Modern Bungalow",
    location: "DHA Phase 6, Lahore",
    price: "$320,000",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=80",
    beds: 5,
    baths: 4,
    area: "350m²",
    description: "A beautifully designed contemporary bungalow in DHA Phase 6, Lahore. Featuring spacious interiors, premium finishes, and a landscaped garden in one of Lahore's most sought-after neighborhoods.",
    features: ["Landscaped Garden", "Home Theater", "Modern Kitchen", "Solar Panels", "Garage", "Security"],
    country: "Pakistan",
  },
  {
    id: 5,
    type: "Rent",
    title: "Beirut Sea View Apartment",
    location: "Achrafieh, Beirut",
    price: "$3,500/mo",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80",
    beds: 2,
    baths: 2,
    area: "110m²",
    description: "A chic and elegant apartment in the prestigious Achrafieh neighborhood of Beirut, offering stunning Mediterranean sea views, high-end finishes, and a prime central location.",
    features: ["Sea View", "Balcony", "Modern Kitchen", "24/7 Security", "Parking", "Elevator"],
    country: "Lebanon",
  },
  {
    id: 6,
    type: "Sale",
    title: "Abu Dhabi Compound Villa",
    location: "Khalifa City, Abu Dhabi",
    price: "$750,000",
    image: "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800&q=80",
    beds: 6,
    baths: 5,
    area: "500m²",
    description: "A grand family villa within an exclusive gated compound in Khalifa City, Abu Dhabi. Offering generous living space, private garden, and access to community amenities in a secure, family-friendly environment.",
    features: ["Gated Compound", "Private Garden", "Driver's Room", "Maid's Room", "Pool Access", "Clubhouse"],
    country: "UAE",
  },
];